name: pull

on:
  push:
    branches:
      - master

jobs:
  build-images:
    name: Pull code from master to q-flex.ru
    runs-on: ubuntu-latest

    steps:
      - name: pull newest code to q-flex.ru from master
        env:
          UPDATER_KEY: ${{ secrets.UPDATER_KEY }}
        run: curl https://hooks.q-flex.ru/update/pull-code/${UPDATER_KEY}
